name: GitHub Pages

on:
  push:
    branches:
      - main  # 博客根目录的默认分支，这里是main，有时也是master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.107.0'  # 填写你的hugo版本，可用hugo version查看
          extended: true          # 如果你使用的不是extended版本的hugo，将true改为false

      - name: Build
        run:
          - hugo --minify
          - cp -r gh-pages/* public/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}  # 注意填写main或者master
        with:
          github_token: ${{ secrets.GH_ACT_TOKEN}} # 如果secret取了其他名称，将GH_ACT_TOKEN替换掉
          publish_dir: ./public
          # cname: www.example.com        # 填写你的自定义域名。如果没有用自定义域名，注释掉这行
